cluster:
  mkdir -p log/{rule} &&
  sbatch
    --cpus-per-task=1
    --mem={resources.mem_mb}
    --time={resources.time}
    --output=log/{rule}/{jobid}.out
    --error=log/{rule}/{jobid}.err

default-resources:
  - partition=cpuq
  - mem_mb=2000
  - disk_mb=2000
  - time=600

restart-times: 2
jobs: 800
max-jobs-per-second: 20
latency-wait: 30
keep-going: True